name: setup
description: ""

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version: 16.x
    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile
