name = "ogp-messenger"
type = "javascript"

zone_id = ""
account_id = ""
route = ""
workers_dev = true

[site]
bucket = "./public"
entry-point = "."

[build]
command = "yarn run build"

[build.upload]
format="service-worker"
