name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/_build.yml

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: setup
        uses: ./.github/actions/setup

      - name: Deploy
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: yarn run deploy
